# Generated by Django 4.1.2 on 2022-11-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise_tracker', '0002_alter_partyvalidity_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
