# Generated by Django 4.1.2 on 2022-11-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise_tracker', '0003_alter_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='parties'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='politician'),
        ),
    ]
