# Generated by Django 4.1.2 on 2022-11-24 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promise_tracker', '0005_alter_party_logo_alter_politician_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyvalidity',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promise_tracker.party'),
        ),
        migrations.AlterField(
            model_name='partyvalidity',
            name='politician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promise_tracker.politician'),
        ),
    ]
