# Generated by Django 4.1.2 on 2022-11-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise_tracker', '0006_alter_partyvalidity_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
