# Generated by Django 4.1.2 on 2022-12-13 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promise_tracker', '0008_alter_rating_options_promise_politician_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='title',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='promise',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politician_promises', to='promise_tracker.politician'),
        ),
    ]
