# Generated by Django 4.1.2 on 2022-12-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promise_tracker', '0010_user_created_user_is_anonymous_user_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='party',
        ),
        migrations.AddField(
            model_name='politician',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='promise_tracker.party'),
        ),
    ]
