# Generated by Django 4.1.2 on 2022-12-23 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promise_tracker', '0011_remove_politician_party_politician_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promise',
            name='fuentes',
            field=models.ManyToManyField(blank=True, default=None, related_name='promise_sources', to='promise_tracker.source'),
        ),
    ]
