# Generated by Django 4.1.2 on 2022-12-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise_tracker', '0012_alter_promise_creator_alter_promise_fuentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='fuentes',
        ),
        migrations.RemoveField(
            model_name='promise',
            name='fuentes',
        ),
        migrations.AddField(
            model_name='evidence',
            name='source',
            field=models.CharField(default='', max_length=200),
        ),
    ]
